<?php
/**
 * Plugin Name:       Immortel Schema Bridge
 * Description:       Stores JSON-LD generated by Immortel on each post and prints it in the page head, merging with Yoast SEO or Rank Math when present.
 * Version:           1.0.0
 * Requires at least: 5.6
 * Requires PHP:      7.4
 * Author:            Immortel
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 *
 * WordPress has no metafield-render concept like Shopify, so publishing JSON-LD from an
 * external system has no guaranteed destination. This plugin provides one: a REST-writable
 * post meta field that is printed into wp_head, and merged into an SEO plugin's graph when
 * one owns structured data on the site.
 *
 * @package ImmortelSchemaBridge
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'IMMORTEL_SB_VERSION', '1.0.0' );
define( 'IMMORTEL_SB_NAMESPACE', 'immortel/v1' );
define( 'IMMORTEL_SB_META_JSON_LD', 'immortel_json_ld' );
define( 'IMMORTEL_SB_META_PAYLOAD', 'immortel_payload' );
define( 'IMMORTEL_SB_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );

require_once IMMORTEL_SB_PLUGIN_DIR . 'includes/rest-status.php';
require_once IMMORTEL_SB_PLUGIN_DIR . 'includes/seo-bridge.php';

/**
 * Register the meta fields Immortel writes to.
 *
 * `show_in_rest` is what makes them settable via `POST /wp/v2/posts` with a `meta` object.
 * The auth callback requires `edit_posts` so the credential doing the publishing is the
 * same one authorized to create the post in the first place.
 */
function immortel_sb_register_meta() {
	$common = array(
		'single'        => true,
		'type'          => 'string',
		'show_in_rest'  => true,
		'auth_callback' => static function () {
			return current_user_can( 'edit_posts' );
		},
	);

	register_post_meta(
		'post',
		IMMORTEL_SB_META_JSON_LD,
		array_merge(
			$common,
			array( 'description' => 'JSON-LD graph rendered into the page head.' )
		)
	);

	register_post_meta(
		'post',
		IMMORTEL_SB_META_PAYLOAD,
		array_merge(
			$common,
			array( 'description' => 'Immortel generation metadata for this post.' )
		)
	);
}
add_action( 'init', 'immortel_sb_register_meta' );

/**
 * Read and decode the stored graph for a post.
 *
 * @param int $post_id Post ID.
 * @return array|null Decoded graph, or null when absent or malformed.
 */
function immortel_sb_get_graph( $post_id ) {
	$raw = get_post_meta( $post_id, IMMORTEL_SB_META_JSON_LD, true );
	if ( empty( $raw ) || ! is_string( $raw ) ) {
		return null;
	}

	$decoded = json_decode( $raw, true );
	if ( JSON_ERROR_NONE !== json_last_error() || ! is_array( $decoded ) ) {
		return null;
	}

	return $decoded;
}

/**
 * Print the stored JSON-LD into the head of singular posts.
 *
 * Skipped entirely when an SEO plugin is handling the graph — in that case
 * includes/seo-bridge.php merges our nodes into theirs, and printing here as well would
 * emit two competing Article nodes for the same URL.
 */
function immortel_sb_print_head() {
	if ( ! is_singular( 'post' ) ) {
		return;
	}
	if ( immortel_sb_seo_plugin_active() ) {
		return;
	}

	$graph = immortel_sb_get_graph( get_the_ID() );
	if ( null === $graph ) {
		return;
	}

	// wp_json_encode escapes the unicode/slash sequences that could otherwise close the tag.
	$json = wp_json_encode( $graph, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
	if ( false === $json ) {
		return;
	}

	echo "\n<script type=\"application/ld+json\" data-immortel=\"1\">" . $json . "</script>\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action( 'wp_head', 'immortel_sb_print_head', 5 );
